# Generated by Django 4.0.5 on 2022-06-22 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_rename_bikesposts_bikespost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bikespost',
            new_name='Post',
        ),
    ]
