# Generated by Django 4.0.5 on 2022-06-22 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_rename_post_bikepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_bikeposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bikeimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('alt', models.TextField(max_length=140)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_bikeimages', to='blog.bikepost')),
            ],
        ),
    ]
