# Generated by Django 4.0.5 on 2022-06-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_bikepost_author_bikeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biketable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('releaseyear', models.DateField()),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bikeimage',
            name='postid',
        ),
        migrations.AddField(
            model_name='bikepost',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.bikeimage'),
        ),
        migrations.AddField(
            model_name='bikepost',
            name='table',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.biketable'),
        ),
    ]
