# Generated by Django 4.0.5 on 2022-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_biketable_remove_bikeimage_postid_bikepost_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biketable',
            name='model',
        ),
        migrations.RemoveField(
            model_name='biketable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='biketable',
            name='releaseyear',
        ),
        migrations.AddField(
            model_name='biketable',
            name='Ask_questions',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Clutch',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Color_options',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Comments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Cooling_system',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Displacement',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Dry_weight',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Engine_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Factory_warranty',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Finance_options',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Frame_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Front_brakes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Front_suspension',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Front_tire',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Fuel_capacity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Fuel_consumption',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Fuel_system',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Gearbox',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Greenhouse_gases',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Insurance_costs',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Maintenance',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Model',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Overall_height',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Overall_length',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Overall_width',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Parts_finder',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Power',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Power_weight_ratio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Rating',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Rear_brakes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Rear_suspension',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Rear_tire',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Related_bikes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Seat_height',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Starter',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Top_speed',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Transmission_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Update_specs',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Wheelbase',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketable',
            name='Year',
            field=models.CharField(default='', max_length=200),
        ),
    ]
